// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Övning16Industriellmaskinpark.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230216131643_AttilaStarkenius16.2.2023.migratingDbSetIndustrialMachine")]
    partial class AttilaStarkenius1622023migratingDbSetIndustrialMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Övning_16___Industriell_maskinpark__.Client.Models.IndustrialMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("currentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("latestDataSentFromMachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IndustrialMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
